config/routes.rb
RailsJunkies::Application.routes.draw do
  require 'sidekiq/web'

  get 'hashtags/',              to: 'hashtags#index', as: :hashtags
  get 'hashtags/:hashtag',      to: 'hashtags#show', as: :hashtag  
  get 'mentions/users',         to: 'mentions#users'
  get 'follow_team/hide',       to: 'follow_team#hide', as: :hide_follow_team
  get 'latest-updates',         to: 'activities#latest_updates', 
                                as: :latest_updates
  get 'about',                  to: 'static#about'
  get 'rsvps/paginate',         to: 'rsvps#paginate'
  get 'notifications/paginate', to: 'notifications#paginate'
  get 'messages/paginate',      to: 'conversations#paginate'
  get 'contact',                to: 'static#contact'
  get 'privacy',                to: 'static#privacy'
  get 'tos',                    to: 'static#tos'
  get 'search',                 to: 'search#index'
  get 'search/users',           to: 'search#users'
  get 'search/hashtags',        to: 'search#hashtags'
  get 'messages',               to: 'conversations#index'
  get 'notifications/dropdown', to: 'notifications#dropdown'
  get 'messages/dropdown',      to: 'conversations#dropdown'
  get 'profile/edit',           to: 'profiles#edit'
  get 'profile/edit/header',    to: 'profiles#edit_header'
  get 'nearby/events',          to: 'nearby#events'
  get 'nearby/summoners',       to: 'nearby#summoners'
  get 'nearby/posts',           to: 'nearby#posts'
  post 'embedly',               to: 'posts#embedly', as: 'embedly'
  resources :mentions, only: [:index]
  resources :notifications
  resources :activities, only: [:index]
  resources :events do
    resources :rsvps
    get 'hosting', on: :collection
    get 'rsvps', on: :collection
    put "update_image", to: 'events#update_image'
    delete "remove_image", to: 'events#remove_image'
  end
  #resources :invitations, only: [:create]
  resources :users, only: [:index, :show, :update] do
    resources :profiles
    get 'likes', to: 'users#likes'
    get 'favorites', to: 'profiles#favorites'
    get 'about', to: 'profiles#show'
    get 'photos', to: 'photos#index'
    get 'followers', to: 'follows#followers'
    get 'following', to: 'follows#following'
    get 'friends', to: 'follows#friends'
    get 'matches', to: 'users#matches'
    delete 'remove_avatar', to: 'profiles#remove_avatar'
    put 'update_avatar', to: 'profiles#update_avatar'
    put 'update_header', to: 'profiles#update_header'
  end
  resources :photos do
    resources :comments
    resources :likes, only: [:index, :create]
    delete 'likes', to: 'likes#destroy'
  end
  resources :champions
  resources :spells
  resources :items
  resources :status_messages, only: [:new, :create, :update]
  resources :messages, only: [:new, :create, :show]
  resources :conversations, only: [:index] do
    member do
      post :reply
    end
  end
  post 'follow/:id', to: 'follows#create', as: :follow
  delete 'follow/:id', to: 'follows#destroy', as: :follow
  resources :posts, only: [:show, :destroy] do
    resources :comments
    resources :favorites, only: [:index, :create]
    resources :likes, only: [:index, :create]
    resources :shares, only: [:index, :new, :create]
    delete 'likes', to: 'likes#destroy'
    delete 'favorites', to: 'favorites#destroy'
    delete 'shares', to: 'shares#destroy'
  end
  resources :locations
  resources :summoners do
    get 'verify', to: 'summoners#verify'
  end
  get 'summoner_status/:job_id', to: 'summoners#verification_status'
  devise_for :users, path: '', skip: [:registrations, :invitations], path_names: {sign_in: 'login', sign_out: 'logout', password: 'password-reset', confirmation: 'confirm-account'}, controllers: {confirmations: 'confirmations'}
  as :user do
    get 'register', to: 'users/registrations#new', as: 'new_user_registration'
    post 'register', to: 'devise/registrations#create', as: 'user_registration'
    get 'users/cancel', to: 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'settings', to: 'users#edit', as: 'edit_user_registration'
    put 'settings', to: 'users#update'
    get 'invite/accept', to: 'users/invitations#edit', as: 'accept_user_invitation'
    get 'invite/remove', to: 'devise/invitations#destroy', as: 'remove_user_invitation'
    post 'invite', to: 'users/invitations#create', as: "user_invitation"
    get 'invite/new', to: 'users/invitations#new', as: "new_user_invitation"
    put 'invite', to: 'users/invitations#update'
    put 'confirm', to: 'confirmations#confirm'
  end
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
  end
  mount Sidekiq::Web => '/sidekiq'
  authenticated :user do 
    root to: "dashboard#index", as: "authenticated_root"
  end
  
  root to: "static#index"
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :get_mailbox
  before_filter :get_conversation, only: [:show, :reply]

  def index
  end

  def reply
    @receipt = current_user.reply_to_conversation(@conversation, params[:body])
    respond_to do |format|
      format.js
    end
  end

  def dropdown
    @mailbox = current_user.mailbox
    @conversations = @mailbox.inbox.order("id DESC").page(params[:conversations_page]).per_page(7)
    respond_to do |format|
      format.js
    end
  end

  def paginate
    @mailbox = current_user.mailbox
    @conversations = @mailbox.inbox.order("id DESC").page(params[:conversations_page]).per_page(7)
    respond_to do |format|
      format.js
    end
  end

private

  def get_mailbox
    @mailbox = current_user.mailbox
    @conversations = @mailbox.conversations
  end

  def get_conversation
    @conversation = @conversations.find(params[:id])
  end

end

app/views/conversations/_conversation.erb
<%= link_to message_path(conversation), class: "list-group-item conversation unread clearfix" do %>
  <img src="<%= conversation.participants.reject {|p| p.id == current_user.id}.first.profile.image? ? conversation.participants.reject {|p| p.id == current_user.id}.first.profile.image_url(:thumb_small) : asset_path('small-user.png') %>" width="36" class="conversation-avatar pull-left">
  <div class="conversation-info pull-left">
    <div class="conversation-name">
      <%= conversation.participants.reject {|p| p.id == current_user.id}.first.full_name %> <span class="friend-username">@<%= conversation.participants.reject {|p| p.id == current_user.id}.first.username %></span>
    </div>
    <div class="conversation-preview">
      <%= conversation.subject %>
    </div>
  </div>                  
<% end %>

app/views/conversations/_icon.html.erb
<%= image_tag 'icons/icons_inbox.png' %>
<% unless current_user.unread_inbox_count == 0  %>
  <span class="nav-badge notification-counter"><%= current_user.unread_inbox_count %></span>
<% end %> 

app/views/conversations/dropdown.js.erb
var dropdown = $(".messages-menu");
var icon = $(".messages-toggle");
dropdown.html("<%= j render 'conversations/dropdown/content' %>");

<% unless current_user.unread_inbox_count == 0 %>
  <% current_user.mailbox.inbox(read: false).each do |c| %>
    <% c.mark_as_read(current_user) %>
  <% end %>
<% end %>

icon.html("<%= j render 'conversations/icon' %>");

app/views/conversations/index.html.erb
<div class="container margin-bottom-140">
  <div class="col-md-3 col-padding">
    <div class="row">
      <div class="col-md-12">
        <div class="module">
          <div class="conversations-list">
            <div class="filter left-inner-addon">
              <i class="glyphicon glyphicon-search"></i>
              <input type="text" class="form-control" placeholder="Filter">
            </div>
            <div class="conversations">
              <ul class="list-group">  
                <% @conversations.each do |conversation| %>      
                  <%= render "conversations/conversation", conversation: conversation %>
                <% end %> 
              </ul>                                
            </div>
          </div>                
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-9 col-padding">
    <div class="row">
      <div class="col-md-12">
        <% if @conversations.empty? %>
        <div class="module">
          <center>No messages yet!</center>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/conversations/paginate.js.erb
$('.messages-dropdown-container').append('<% @conversations.each do |conversation| %><%= j render "conversations/dropdown/conversation", conversation: conversation %><% end %>');

<% if @conversations.next_page %>
  $('.messages-menu .pagination').replaceWith('<%= j will_paginate @conversations, param_name: :conversations_page, params: { controller: "conversations", action: "paginate"}, renderer: BootstrapPagination::Rails, class: "messages-pagination" %>');
<% else %>
  $('.messages-menu .pagination').remove();
<% end %>

app/views/conversations/reply.js.erb
var messages = $(".messages");
var text_area = $("#body");
var button = $(".conversation-reply input[type=submit]");
messages.append("<%= j render 'messages/message', message: @receipt.message %>");
text_area.val('');
text_area.height('auto');
button.prop('disabled', true);