config/routes.rb
RailsJunkies::Application.routes.draw do
  require 'sidekiq/web'

  get 'hashtags/',              to: 'hashtags#index', as: :hashtags
  get 'hashtags/:hashtag',      to: 'hashtags#show', as: :hashtag  
  get 'mentions/users',         to: 'mentions#users'
  get 'follow_team/hide',       to: 'follow_team#hide', as: :hide_follow_team
  get 'latest-updates',         to: 'activities#latest_updates', 
                                as: :latest_updates
  get 'about',                  to: 'static#about'
  get 'rsvps/paginate',         to: 'rsvps#paginate'
  get 'notifications/paginate', to: 'notifications#paginate'
  get 'messages/paginate',      to: 'conversations#paginate'
  get 'contact',                to: 'static#contact'
  get 'privacy',                to: 'static#privacy'
  get 'tos',                    to: 'static#tos'
  get 'search',                 to: 'search#index'
  get 'search/users',           to: 'search#users'
  get 'search/hashtags',        to: 'search#hashtags'
  get 'messages',               to: 'conversations#index'
  get 'notifications/dropdown', to: 'notifications#dropdown'
  get 'messages/dropdown',      to: 'conversations#dropdown'
  get 'profile/edit',           to: 'profiles#edit'
  get 'profile/edit/header',    to: 'profiles#edit_header'
  get 'nearby/events',          to: 'nearby#events'
  get 'nearby/summoners',       to: 'nearby#summoners'
  get 'nearby/posts',           to: 'nearby#posts'
  post 'embedly',               to: 'posts#embedly', as: 'embedly'
  resources :mentions, only: [:index]
  resources :notifications
  resources :activities, only: [:index]
  resources :events do
    resources :rsvps
    get 'hosting', on: :collection
    get 'rsvps', on: :collection
    put "update_image", to: 'events#update_image'
    delete "remove_image", to: 'events#remove_image'
  end
  #resources :invitations, only: [:create]
  resources :users, only: [:index, :show, :update] do
    resources :profiles
    get 'likes', to: 'users#likes'
    get 'favorites', to: 'profiles#favorites'
    get 'about', to: 'profiles#show'
    get 'photos', to: 'photos#index'
    get 'followers', to: 'follows#followers'
    get 'following', to: 'follows#following'
    get 'friends', to: 'follows#friends'
    get 'matches', to: 'users#matches'
    delete 'remove_avatar', to: 'profiles#remove_avatar'
    put 'update_avatar', to: 'profiles#update_avatar'
    put 'update_header', to: 'profiles#update_header'
  end
  resources :photos do
    resources :comments
    resources :likes, only: [:index, :create]
    delete 'likes', to: 'likes#destroy'
  end
  resources :champions
  resources :spells
  resources :items
  resources :status_messages, only: [:new, :create, :update]
  resources :messages, only: [:new, :create, :show]
  resources :conversations, only: [:index] do
    member do
      post :reply
    end
  end
  post 'follow/:id', to: 'follows#create', as: :follow
  delete 'follow/:id', to: 'follows#destroy', as: :follow
  resources :posts, only: [:show, :destroy] do
    resources :comments
    resources :favorites, only: [:index, :create]
    resources :likes, only: [:index, :create]
    resources :shares, only: [:index, :new, :create]
    delete 'likes', to: 'likes#destroy'
    delete 'favorites', to: 'favorites#destroy'
    delete 'shares', to: 'shares#destroy'
  end
  resources :locations
  resources :summoners do
    get 'verify', to: 'summoners#verify'
  end
  get 'summoner_status/:job_id', to: 'summoners#verification_status'
  devise_for :users, path: '', skip: [:registrations, :invitations], path_names: {sign_in: 'login', sign_out: 'logout', password: 'password-reset', confirmation: 'confirm-account'}, controllers: {confirmations: 'confirmations'}
  as :user do
    get 'register', to: 'users/registrations#new', as: 'new_user_registration'
    post 'register', to: 'devise/registrations#create', as: 'user_registration'
    get 'users/cancel', to: 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'settings', to: 'users#edit', as: 'edit_user_registration'
    put 'settings', to: 'users#update'
    get 'invite/accept', to: 'users/invitations#edit', as: 'accept_user_invitation'
    get 'invite/remove', to: 'devise/invitations#destroy', as: 'remove_user_invitation'
    post 'invite', to: 'users/invitations#create', as: "user_invitation"
    get 'invite/new', to: 'users/invitations#new', as: "new_user_invitation"
    put 'invite', to: 'users/invitations#update'
    put 'confirm', to: 'confirmations#confirm'
  end
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
  end
  mount Sidekiq::Web => '/sidekiq'
  authenticated :user do 
    root to: "dashboard#index", as: "authenticated_root"
  end
  
  root to: "static#index"
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :user, :notifiable, :notifier
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
  belongs_to :notifier, polymorphic: true

  scope :unread, -> { where(read: false) }

  default_scope order("created_at DESC")

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  include FeedSidebar
  
  before_filter :authenticate_user!
  before_filter :find_notifications

  def index
    @notifications.unread.update_all(read: true) if @notifications.unread.present?
    @notifications = @notifications.page(params[:main_pagination]).per_page(17)   
  end

  def dropdown
    @notifications = @notifications.page(params[:notifications_page]).per_page(7)
    respond_to do |format|
      format.js
    end
  end

  def paginate
    @notifications = @notifications.page(params[:notifications_page]).per_page(7)
    respond_to do |format|
      format.js
    end
  end

private
  def find_notifications
    @notifications = current_user.notifications.order("id DESC")
  end
end

app/views/notifications/_dropdown_content.html.erb
<% if @notifications.present? %>
  <p class="notification-heading">
    <%= image_tag "icons/notifications/alert.png" %> 
    <%= @notifications.unread.count %> New <%= "Notification".pluralize(@notifications.unread.count) %>
  </p>
  <div class="notification-dropdown-container scrollbar">
    <% @notifications.each do |notification| %>
      <%= render "notifications/#{notification.notifiable_type.underscore}/dropdown", notification: notification %>
    <% end %>
  </div>
  <center><%= will_paginate @notifications, param_name: :notifications_page, params: { controller: "notifications", action: "paginate"}, renderer: BootstrapPagination::Rails, class: "notifications-pagination" if @notifications.present? %></center>  
<% else %>
  <p class="notification-heading">
    <%= image_tag "icons/notifications/alert.png" %> 0 New Notifications
  </p>
<% end %>
<dv class="notifications-more">
  <center><%= link_to "View More", notifications_path %></center>
</dv>

app/views/notifications/_icon.erb
<%= image_tag 'icons/icons_alerts.png', width: 28, height: 28 %>
<% if current_user.notifications.unread.present? %>
  <span class="nav-badge notification-counter"><%= current_user.notifications.unread.count %></span>
<% end %> 

app/views/notifications/_notification.html.erb
<div class="latest-update clearfix">
  <img src="<%= notification.notifier.profile.image? ? notification.notifier.profile.image_url(:thumb_small) : asset_path("small-user.png") %>" width="25" height="22" class="pull-left">
  <div class="update-body">
    <%= link_to notification.notifier.full_name, notification.notifier %> <%= render "notifications/#{notification.notifiable_type.underscore}/listing", notification: notification %>
  </div>
  <div class="update-date pull-right">
    <%= local_time_ago(notification.created_at) %>
  </div>
</div>

app/views/notifications/dropdown.js.erb
var dropdown = $(".notification-menu");
var icon = $(".notification-toggle");
dropdown.html("<%= j render 'notifications/dropdown_content' %>");

<% current_user.notifications.unread.update_all(read: true) if current_user.notifications.unread.present? %>
icon.html("<%= j render 'notifications/icon' %>");

app/views/notifications/index.html.erb
<div class="container">
  <div class="col-md-3 col-padding">
    <%= render 'dashboard/sidebar' %>
  </div>
  <div class="col-md-6 col-padding">
    <div class="row">
      <div class="col-md-12">
        <div class="module search-results-for">
          <ul class="nav nav-pills">
            <li><%= link_to "Latest Updates", latest_updates_path %></li>
            <li><%= link_to "Notifications", notifications_path %></li>
            <li><%= link_to "Mentions", mentions_path %></li>
            <li><%= link_to "Your Activity", activities_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="module">
          <div class="notifications">
            <% @notifications.each do |notification| %>
              <%= render "notifications/notification", notification: notification %>
            <% end %>
          </div>
          <center><%= will_paginate @notifications, renderer: BootstrapPagination::Rails, param_name: "main_pagination", class: "feed-pagination" if @notifications.present? %></center>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-padding">
  </div>
</div>

app/views/notifications/index.js.erb
$('.notifications').append('<% @notifications.each do |notification| %><%= j render "notifications/notification", notification: notification %><% end %>');

<% if @notifications.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @notifications, renderer: BootstrapPagination::Rails, param_name: "main_pagination", class: "feed-pagination" %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/notifications/paginate.js.erb
$('.notification-dropdown-container').append('<% @notifications.each do |notification| %><%= j render "notifications/#{notification.notifiable_type.underscore}/dropdown", notification: notification %><% end %>');

<% if @notifications.next_page %>
  $('.notification-menu .pagination').replaceWith('<%= j will_paginate @notifications, param_name: :notifications_page, params: { controller: "notifications", action: "paginate"}, renderer: BootstrapPagination::Rails, class: "notifications-pagination" %>');
<% else %>
  $('.notification-menu .pagination').remove();
<% end %>